### ISSUE TITLE
Fixtures with pytest.mark.fixture() with parametrize in test functions

### ISSUE THREAD

**Issue by Brachi** [TvoroG/pytest-fixture-mark#2]
Currently the example below doesn't work. I'd expect to produce the equivalent of the last test function.
Probably the parametrize decorator should take precedence over the parametrized fixture, as the other parametrization is not explicit.
Hope to help in development soon.

``` python
import pytest


@pytest.fixture(params=[1, 2, 3])
def one(request):
    return request.param


@pytest.fixture(params=[pytest.mark.fixture('one')])
def as_str(request):
    return str(request.getfixturevalue('one'))



# doesn't work. Fixture 'a'/'b'/'c' not found
@pytest.mark.parametrize('val', ('a', 'b', 'c'))
def test_as_str(val, as_str):
    combined = ''.join((val, as_str))
    assert combined in {'a1', 'a2', 'a3', 'b1', 'b2', 'b3', 'c1', 'c2', 'c3'}


# test_as_str expected
@pytest.mark.parametrize('val_2', ('1', '2', '3'))
@pytest.mark.parametrize('val_1', ('a', 'b', 'c'))
def test_parametrize(val_1, val_2):
    combined = ''.join((val_1, val_2))
    assert combined in {'a1', 'a2', 'a3', 'b1', 'b2', 'b3', 'c1', 'c2', 'c3'}
```

**Comment by TvoroG** [comment]
I fixed it on `lazy_fixture` branch by using own object instead of mark. The problem is `pytest` [extracts](https://github.com/pytest-dev/pytest/blob/c60854474abacd62b537b2cf759e305367afb75e/_pytest/mark.py#L286) arg values from mark, so i can't tell exactly on which objects fixture mark was applied. The easiest way to fix that problem is to implement plugin through own object (`pytest.lazy_fixture`) instead of `pytest.mark.fixture`. `pytest` will not touch it. The plugin code will be also a little bit simplified and all previous examples, use cases will work with `lazy_fixture` too.
What do you think?

**Comment by Brachi** [comment]
Thanks @TvoroG I'll test it soon and give you feedback.
